### ISSUE TITLE
How to create mocap motion file using SMPL params?

### ISSUE THREAD

**Issue by mariolew** [xbpeng/DeepMimic#39]
Hi, I'm trying to reproduce SFV, and now I got 3D poses of some actions like backflip. I tried to convert the 3D mesh to mocap data, and it seems the converted motion file is correct in the bullet simulator. However, I cannot get well trained model for backflip, I know that SFV uses ASI, but as you show in the demo, model can also be well trained using RSI.  

So, is there anything I should pay attention to in converting SMPL mesh to mocap file? Should the feet of the robot be under the ground in the first frame?

**Comment by bsivanantham** [comment]
@mariolew can you please help me set up the poses?? I really stuck i getting some error ..

**Comment by xbpeng** [comment]
@mariolew can you post an example of the motion file? I can take a look. The character's links should not be under the ground in any of the frames.

**Comment by mariolew** [comment]
@xbpeng Hi, I've post my motion file for backflip A here https://github.com/mariolew/motion_file_debug/blob/master/test_motion.txt. The file was generated using json.dump, so it might not be in a pretty format, sorry for that.

**Comment by mariolew** [comment]
I tried again and failed, I believe there must be something wrong with my motion file, would you please give me some help? @xbpeng

**Comment by xbpeng** [comment]
how are you getting the root position from the pose estimator? I think the root motion currently seems a bit odd. The character seems to be moving forward during the backflip. The y position also doesn't seem to be changing much during the flip. I think all the jittering in the ref motion also makes it harder to imitate, because directly sampling initial states from the ref motion, can also initialize the character to some very large velocities. Are you applying any smoothing to the ref motion? Like what we did in the motion reconstruction stage. Some smoothing can make RSI work a lot better.

**Comment by mariolew** [comment]
@xbpeng I may get the x value of the root position wrong, so that the character seems to be moving forward. I got the root position directly from the 2D pose estimation results(the mean position of two hips),  and then normalize the value of the root position to make the character roughly standing on the ground.

Actually, this motion file is converted from the motion reconstruction results. As for backflip, motion reconstruction does not make too much difference, but as for cartwheel, motion reconstruction greatly improves the raw 3D pose estimation.

I'd fix the x value problem and try again. Thanks and I'll comment here once I get the new results.

**Comment by mariolew** [comment]
@xbpeng Hi, Jason. I got correct result once I fixed the root position problem. Thanks a lot.

**Comment by xbpeng** [comment]
great to hear!

**Comment by Zju-George** [comment]
@mariolew @xbpeng  what is RSI and ASI stand for?? I'm stuck..
