### ISSUE TITLE
 I want to create my own motion file,can you told me how to import bvh file?

### ISSUE THREAD

**Issue by skylbc** [xbpeng/DeepMimic#50]

**Comment by xbpeng** [comment]
You'll need to retarget your bvh motions to the format of the files in data/motions/. There is some info on how to do this in the README. It can be a pretty tricky process though, so let me know if any particular questions come up.

**Comment by erwincoumans** [comment]
Here is some example conversion code to DeepMimic json mocap files. It doesn't accept BVH but VideoPose3D, but it gives you an example for the conversion:

https://github.com/bulletphysics/bullet3/tree/master/examples/pybullet/gym/pybullet_envs/deep_mimic/mocap

**Comment by skylbc** [comment]
@erwincoumans Thank you , I will try later.

**Comment by jiaqixuac** [comment]
@erwincoumans Thanks for your information.

However, after I converted the VideoPose3D preprocessed data showed in the link above to the json mocap file for DeepMimic, I found that due to the lack of gravity effect in the converted json, it's difficult for the character to imitate motions while standing on the ground.

So, I think even though we can convert a file in that way, the correct way is still to use retargeting.
